-- ONE TO ONE
-- ONE TO MANY
-- MANY TO MANY

CREATE TABLE Person(
     Id INT PRIMARY KEY IDENTITY(1,1),
	 FullName NVARCHAR(100) NOT NULL,
	 Age INT NOT NULL,
	 Email NVARCHAR(80) NOT NULL UNIQUE
);

-- ONE TO ONE 

CREATE TABLE TelegramAccount(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Login] NVARCHAR(32) NOT NULL,
	[Password] NVARCHAR(32) NOT NULL,
	PersonId INT FOREIGN KEY REFERENCES Person(Id) NOT NULL UNIQUE
);

-- ONE TO MANY
CREATE TABLE Message(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Text] TEXT NOT NULL,
	AcountSender INT FOREIGN KEY REFERENCES TelegramAccount(Id) NOT NULL,
	AcountRecipent INT FOREIGN KEY REFERENCES TelegramAccount(Id) NOT NULL,
);


--MANY TO MANY
CREATE TABLE [Group](
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(100) NOT NULL
);

CREATE TABLE AccountInGroup(

	Id INT PRIMARY KEY IDENTITY(1,1),
	AcoountId INT FOREIGN KEY REFERENCES TelegramAccount(Id) NOT NULL,
	GroupId INT FOREIGN KEY REFERENCES [Group](Id) NOT NULL

);